import ClientProvider from '@/components/ClientProvider';
import { ThemeProvider } from '@/components/theme-provider';
import { getCurrentUser } from '@/lib/serverFunctions';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
          <ClientProvider ssrUser={user}>{children}</ClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
